In [1]:
# Import Numpy Library
import numpy as np

In [2]:
# create numpy array
a = np.array([1, 2, 3, 4, 5])

In [3]:
print(a)

[1 2 3 4 5]


In [4]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [5]:
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
# create ones, zeros ndarray
ones = np.ones((3, 4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
ones_int = np.ones((4, 4), dtype=int)
ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [9]:
# create full ndarray
full = np.full((3, 3), 13.0, dtype=int)
full

array([[13, 13, 13],
       [13, 13, 13],
       [13, 13, 13]])

In [10]:
# create arange ndarray
c = np.arange(1, 10, dtype=int)
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
d = np.arange(1, 10, 2, dtype=int)
d

array([1, 3, 5, 7, 9])

In [12]:
e = np.arange(100, 0, -5, dtype=int)
e

array([100,  95,  90,  85,  80,  75,  70,  65,  60,  55,  50,  45,  40,
        35,  30,  25,  20,  15,  10,   5])

In [13]:
f = np.arange(0, 100, 2, dtype=int)
f

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [14]:
# create linspace ndarray
lin_array = np.linspace(1, 4)
lin_array

array([1.        , 1.06122449, 1.12244898, 1.18367347, 1.24489796,
       1.30612245, 1.36734694, 1.42857143, 1.48979592, 1.55102041,
       1.6122449 , 1.67346939, 1.73469388, 1.79591837, 1.85714286,
       1.91836735, 1.97959184, 2.04081633, 2.10204082, 2.16326531,
       2.2244898 , 2.28571429, 2.34693878, 2.40816327, 2.46938776,
       2.53061224, 2.59183673, 2.65306122, 2.71428571, 2.7755102 ,
       2.83673469, 2.89795918, 2.95918367, 3.02040816, 3.08163265,
       3.14285714, 3.20408163, 3.26530612, 3.32653061, 3.3877551 ,
       3.44897959, 3.51020408, 3.57142857, 3.63265306, 3.69387755,
       3.75510204, 3.81632653, 3.87755102, 3.93877551, 4.        ])

In [15]:
lin_array.size

50

In [16]:
lin_array2 = np.linspace(11, 2, 7, dtype=int)
lin_array2

array([11,  9,  8,  6,  5,  3,  2])

In [17]:
lin_array3 = np.linspace(-9, 11, 20, dtype=int)
lin_array3

array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 11])

In [18]:
# create eye ndarray
eye_array1 = np.eye(3, dtype=int)
eye_array1

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [19]:
eye_array2 = np.eye(5, dtype=int)
eye_array2

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [20]:
eye_array3 = np.eye(4, 5, 1, dtype=int)
eye_array3

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [21]:
eye_array4 = np.eye(3, 3, -1, dtype=int)
eye_array4

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0]])

In [22]:
# create empty ndarray
empty_array1 = np.empty((3, 3))
empty_array1

array([[0.00000000e+000, 1.63041663e-322, 0.00000000e+000],
       [0.00000000e+000, 4.00766127e+175, 1.63305012e+185],
       [4.90466174e-062, 6.50335587e-091, 4.65862924e-033]])

In [23]:
empty_array2 = np.empty((3, 3), dtype=int)
empty_array2

array([[                  0,                  33,                   0],
       [                  0, 7233978562993192960, 7377801527420281144],
       [3689623705486635565, 3257565106039239525, 4123098653678188387]])

In [24]:
# numpy random number
random_num = np.random.randint(50)
random_num

23

In [25]:
# create random number ndarray (0-1)
random_array1 = np.random.rand(6, 3)
random_array1

array([[0.87195795, 0.92417172, 0.08312179],
       [0.90704075, 0.21356127, 0.22947246],
       [0.71951723, 0.21399446, 0.59719438],
       [0.2780719 , 0.0730392 , 0.42938308],
       [0.83350262, 0.02684983, 0.8546678 ],
       [0.27243208, 0.17990169, 0.08062467]])

In [26]:
random_array2 = np.random.rand(3, 2, 3)
random_array2

array([[[0.85621605, 0.3386321 , 0.05296185],
        [0.25013533, 0.48370413, 0.47315951]],

       [[0.65201822, 0.6571147 , 0.699676  ],
        [0.71017467, 0.17085933, 0.10013553]],

       [[0.59511353, 0.09774577, 0.52419511],
        [0.25846245, 0.40462996, 0.11802282]]])

In [27]:
random_array2[1:]

array([[[0.65201822, 0.6571147 , 0.699676  ],
        [0.71017467, 0.17085933, 0.10013553]],

       [[0.59511353, 0.09774577, 0.52419511],
        [0.25846245, 0.40462996, 0.11802282]]])

In [28]:
# create random randint ndarray
randint_array1 = np.random.randint(100, size=(3, 3))
randint_array1

array([[26, 95, 33],
       [92, 27, 56],
       [91, 96, 54]])

In [29]:
randint_array2 = np.random.randint(50, size=(3, 2, 3))
randint_array2

array([[[42, 35,  5],
        [47, 49, 11]],

       [[22,  3, 15],
        [41,  9, 44]],

       [[38, 12,  6],
        [43, 23, 27]]])

In [30]:
randint_array2[2]

array([[38, 12,  6],
       [43, 23, 27]])

In [31]:
# create choice ndarray
choice_array1 = np.random.choice([1, 2, 3], size=(4, 4))
choice_array1

array([[1, 1, 1, 1],
       [3, 1, 3, 3],
       [1, 2, 3, 2],
       [2, 2, 3, 2]])

In [32]:
# Import Random From Numpy
from numpy import random as rd

In [33]:
random = rd.rand(10)
random

array([0.8773164 , 0.40909127, 0.47745715, 0.86508473, 0.52255271,
       0.59460222, 0.98573237, 0.51281904, 0.14571755, 0.1289676 ])

In [34]:
choice_array2 = rd.choice(random, size=(3, 4))
choice_array2

array([[0.8773164 , 0.1289676 , 0.51281904, 0.98573237],
       [0.51281904, 0.40909127, 0.52255271, 0.1289676 ],
       [0.52255271, 0.59460222, 0.14571755, 0.14571755]])

In [35]:
# Assign probability to random and create choice array
choice_array3 = rd.choice([1, 2, 3, 4, 5], p=[0.1, 0.4, 0.2, 0.1, 0.2], size=(4, 4))
choice_array3 # 2 is most probabilities

array([[3, 4, 4, 3],
       [1, 3, 2, 2],
       [4, 3, 2, 3],
       [5, 5, 5, 2]])

In [36]:
# Use shuffle, permutation
array1 = np.arange(10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
rd.shuffle(array1)

In [38]:
array1

array([5, 3, 9, 8, 6, 0, 7, 4, 2, 1])

In [39]:
array2 = np.arange(15)
array2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [40]:
array3 = rd.permutation(array2)
array3

array([12,  2, 11,  1,  9,  5,  3,  4,  8, 10, 13,  7,  6,  0, 14])

In [41]:
array2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])